### ISSUE TITLE
Full Documentation Site GUI Text File Links

### ISSUE THREAD

**Issue by whittenator** [NVIDIA-AI-IOT/jetson-min-disk#6]
The full documentation site referenced here https://nvidia-ai-iot.github.io/jetson-min-disk/ in the removing the GUI section the both text file links for Jetpack 5 and 4 are dead. Can we get new ones?

Thanks

**Comment by tokk-nv** [comment]
Thank you for pointing this out.
Just fixed the links.
https://nvidia-ai-iot.github.io/jetson-min-disk/step1.html#commands-to-copy-for-removing-gui
